# ตั้งค่า H2 Database in memory
# Code ในการ Run H2 Database
# http://localhost:9000/h2-console ->  JDBC URL ใส่ค่าเป็น jdbc:h2:mem:testdb

server:
  port: 9000
spring:
   jpa:
      show-sql: true
   h2:
      console:
         enabled: true
         